const globalItems = [
    "No Item",
    "Abomasite",
    "Absolite",
    "Aerodactylite",
    "Aggronite",
    "Alakazite",
    "Altarianite",
    "Ampharosite",
    "Aspear Berry",
    "Audinite",
    "Babiri Berry",
    "Banettite",
    "Barbaracite",
    "Beedrillite",
    "Big Root",
    "Blastoisinite",
    "Blazikenite",
    "Bright Powder",
    "Cameruptite",
    "Chandelurite",
    "Charizardite X",
    "Charizardite Y",
    "Charcoal",
    "Chesnaughtite",
    "Chimechite",
    "Chilan Berry",
    "Chople Berry",
    "Cheri Berry",
    "Chesto Berry",
    "Clefablite",
    "Coba Berry",
    "Colbur Berry",
    "Crabominite",
    "Damp Rock",
    "Delphoxite",
    "Dragon Fang",
    "Dragoninite",
    "Dragalgite",
    "Drampanite",
    "Eelektrossite",
    "Emboarite",
    "Expert Belt",
    "Excadrite",
    "Faliksite",
    "Fairy Feather",
    "Feraligite",
    "Floettite",
    "Focus Band",
    "Focus Sash",
    "Froslassite",
    "Galladite",
    "Garchompite",
    "Gardevoirite",
    "Gengarite",
    "Glalitite",
    "Glimmoranite",
    "Golurkite",
    "Greninjite",
    "Gyaradosite",
    "Hard Stone",
    "Haban Berry",
    "Hawluchanite",
    "Heat Rock",
    "Heracronite",
    "Houndoominite",
    "Iron Ball",
    "Kangaskhanite",
    "Kasib Berry",
    "King's Rock",
    "Leppa Berry",
    "Lopunnite",
    "Life Orb",
    "Light Ball",
    "Light Clay",
    "Lum Berry",
    "Lucarionite",
    "Magnet",
    "Malamarite",
    "Manectite",
    "Mawilite",
    "Medichamite",
    "Meganiumite",
    "Meowsticite",
    "Metal Coat",
    "Metagrossite",
    "Metronome",
    "Miracle Seed",
    "Muscle Band",
    "Mystic Water",
    "Never-Melt Ice",
    "Occa Berry",
    "Oran Berry",
    "Passho Berry",
    "Payapa Berry",
    "Pecha Berry",
    "Persim Berry",
    "Pidgeotite",
    "Pinsirite",
    "Poison Barb",
    "Pyroarite",
    "Quick Claw",
    "Raichunite X",
    "Raichunite Y",
    "Rawst Berry",
    "Rindo Berry",
    "Roseli Berry",
    "Sablenite",
    "Sceptilite",
    "Scope Lens",
    "Scizorite",
    "Scolipite",
    "Scovillainite",
    "Scraftinite",
    "Sharp Beak",
    "Sharpedonite",
    "Shuca Berry",
    "Shell Bell",
    "Shed Shell",
    "Silver Powder",
    "Silk Scarf",
    "Sitrus Berry",
    "Smooth Rock",
    "Soft Sand",
    "Spell Tag",
    "Staraptite",
    "Starminite",
    "Steelixite",
    "Swampertite",
    "Tanga Berry",
    "Tyranitarite",
    "Twisted Spoon",
    "Venusaurite",
    "Victreebelite",
    "Wacan Berry",
    "White Herb",
    "Wide Lens",
    "Wise Glasses",
    "Yache Berry",
    "Zoom Lens"
];